USE_SUDO

diff --git a/install b/install
--- a/install
+++ b/install
@@ -10,6 +10,12 @@ if [ -z ${GITHUB_PROJECT+x} ]; then
     exit 1
 fi
 
+if [ -z ${USE_SUDO+x} ]; then
+    install_cmd_prefix=""
+else
+    install_cmd_prefix="sudo"
+fi
+
 url=https://github.com/$GITHUB_USER/$GITHUB_PROJECT/releases/latest/download
 version=$(curl -s $url 2>&1 | grep -oE \[0-9\]+\.\[0-9\]+\.\[0-9\]+)
 orig_dir=$(pwd)
@@ -74,26 +80,10 @@ function silent_run
     eval "$@" 2>&3 1>&3
 }
 
-function do_then_sudo
-{
-    eval "$@"
-    if [ $? != 0 ]; then
-        eval "sudo $@"
-    fi
-    if [ $? != 0 ]; then
-        # Preserve user's environment
-        eval "sudo -E $@"
-    fi
-    if [ $? != 0 ]; then
-        # Preserve user's environment
-        eval "sudo env \"PATH=$PATH\" $@"
-    fi
-}
-
 function run_ldconfig
 {
-    if type "ldconfig" >/dev/null 2>&1; then
-        silent_run do_then_sudo ldconfig
+    if type "ldconfig"; then
+        ldconfig
     fi
 }
 
@@ -115,14 +105,14 @@ function succeeded
     rm -rf "$logfile" >/dev/null 2>&1 || true
 }
 
-echo "[0/6] Library($GITHUB_PROJECT==$version)"
+echo "[0/7] Library($GITHUB_PROJECT==$version)"
 cd $tmpdir
 
-echo -n "[1/6] Downloading... "
+echo -n "[1/7] Downloading... "
 silent_run curl -o $tarfile -L $tarurl
 [ $? == 0 ] && echo "done." || failed
 
-echo -n "[2/6] Extracting... "
+echo -n "[2/7] Extracting... "
 [ -e $tarfile ] || failed
 silent_run tar xzf $tarfile || failed
 [ -e ${tarfile%.tar.gz} ] || failed
@@ -131,20 +121,24 @@ silent_run mkdir build || failed
 silent_run cd build
 [ $? == 0 ] && echo "done." || failed
 
-echo -n "[3/6] Configuring... "
+echo -n "[3/7] Configuring... "
 silent_run cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=On ..
 [ $? == 0 ] && echo "done." || failed
 
-echo -n "[4/6] Compiling... "
+echo -n "[4/7] Compiling... "
 silent_run cmake --build . --config Release
 [ $? == 0 ] && echo "done." || failed
 
-echo -n "[5/6] Testing... "
+echo -n "[5/7] Testing... "
 silent_run ctest --output-on-failure -C Release
 [ $? == 0 ] && echo "done." || failed
 
-echo "[6/6] Installing..."
-do_then_sudo cmake --build . --config Release --target install && run_ldconfig
+echo "[6/7] Installing..."
+silent_run $install_cmd_prefix make install
+[ $? == 0 ] && echo "done." || failed
+
+echo "[7/7] Finalizing..."
+silent_run $install_cmd_prefix run_ldconfig
 [ $? == 0 ] && echo "done." || failed
 
 succeeded
