URL

diff --git a/installv2 b/installv2
--- a/installv2
+++ b/installv2
@@ -125,6 +125,7 @@ fi
 
 GITHUB_USER="${GITHUB_PATH[0]}"
 GITHUB_PROJECT="${GITHUB_PATH[1]}"
+URL=https://github.com/$GITHUB_USER/$GITHUB_PROJECT/releases/latest
 # -----------------------------------------------------------------------------
 
 function error
@@ -140,18 +141,17 @@ function abort
 
 function check_project_url_exists
 {
-    local url=https://github.com/$GITHUB_USER/$GITHUB_PROJECT/releases/latest
-    local http_code=$(curl -L -s -o /dev/null -w "%{http_code}" $url)
+    local http_code=$(curl -L -s -o /dev/null -w "%{http_code}" $URL)
     if [ "$http_code" -lt "200" ] || [ "$http_code" -gt "299" ]; then
-        error "page error for <$url>, $http_code"
+        error "page error for <$URL>, $http_code"
         echo >&2
-        echo >&2 "$(curl -L -i $url 2>/dev/null)"
+        echo >&2 "$(curl -L -i $URL 2>/dev/null)"
         exit 1
     fi
 }
 check_project_url_exists
 
-PRJ_VER=$(curl -L -s $url 2>&1 | grep -oE releases\/tag\/\[0-9\]+\.\[0-9\]+\.\[0-9\]+ | head -n 1 | grep -oE \[0-9\]+\.\[0-9\]+\.\[0-9\]+)
+PRJ_VER=$(curl -L -s $URL 2>&1 | grep -oE releases\/tag\/\[0-9\]+\.\[0-9\]+\.\[0-9\]+ | head -n 1 | grep -oE \[0-9\]+\.\[0-9\]+\.\[0-9\]+)
 ORIG_DIR=$(pwd)
 TARFILE=$GITHUB_PROJECT-$PRJ_VER.tar.gz
 TARURL=https://github.com/$GITHUB_USER/$GITHUB_PROJECT/archive/$PRJ_VER.tar.gz
@@ -208,8 +208,8 @@ HEREDOC
 }
 
 WORKDIR=$(mktemp_dir $GITHUB_PROJECT)
-exec 3>"$LOGFILE"
 LOGFILE=$WORKDIR/oneliner.log
+exec 3>"$LOGFILE"
 
 function cleanup
 {
